-- Campaign Analytics Dashboard - Database Setup
-- This SQL script creates the campaigns table and populates it with sample data

-- Create the campaigns table
CREATE TABLE IF NOT EXISTS campaigns (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    clicks INTEGER NOT NULL,
    cost DECIMAL(10, 2) NOT NULL,
    impressions INTEGER NOT NULL
);

-- Create the users table for dashboard login
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT 0
);

-- Insert 10 sample campaigns
INSERT INTO campaigns (id, name, status, clicks, cost, impressions) VALUES
(1, 'Summer Sale', 'Active', 1500, 120.50, 50000),
(2, 'Winter Clearance', 'Paused', 800, 45.00, 20000),
(3, 'Black Friday Special', 'Active', 3200, 450.75, 120000),
(4, 'Spring Collection Launch', 'Active', 2100, 280.30, 75000),
(5, 'Holiday Gift Guide', 'Paused', 950, 65.20, 28000),
(6, 'Back to School Promo', 'Active', 1850, 195.40, 62000),
(7, 'New Year Flash Sale', 'Active', 2950, 380.90, 95000),
(8, 'Valentine''s Day Campaign', 'Paused', 720, 52.15, 18500),
(9, 'Easter Special Offers', 'Active', 1680, 142.60, 54000),
(10, 'Cyber Monday Deals', 'Paused', 2450, 325.80, 88000);

-- Password hashes are generated by backend/auth_utils.py
INSERT INTO users (id, name, email, password_hash, is_admin) VALUES
(1, 'Demo Manager', 'demo@campaign.com', 'd3ad9315b7be5dd53b31a273b3b3aba5defe700808305aa16a3062b76658a791', 0),
(2, 'Admin Manager', 'admin@campaign.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 1);
